all:
  hosts:
    kubemaster:
      ansible_host: 192.168.2.220
      ip: 192.168.2.220
      access_ip: 192.168.2.220
      ansible_user: ansible
    kubenode1:
      ansible_host: 192.168.2.221
      ip: 192.168.2.221
      access_ip: 192.168.2.221
      ansible_user: ansible
    kubenode2:
      ansible_host: 192.168.2.222
      ip: 192.168.2.222
      access_ip: 192.168.2.222
      ansible_user: ansible
  children:
    kube_control_plane:
      hosts:
        kubemaster:
    kube_node:
      hosts:
        kubenode1:
        kubenode2:
    etcd:
      hosts:
        kubemaster:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
