version: '3.8'
networks:
  monitoring:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    volumes:
      - ./src/prometheus:/etc/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/tsdb'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'  
    ports:
      - 9090:9090
    restart: unless-stopped 
    networks: 
      - monitoring     
  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    restart: unless-stopped 
    networks: 
      - monitoring     
  grafana:
    image: grafana/grafana:9.1.1-ubuntu
    container_name: grafana
    volumes:
      - './src/grafana/data:/var/lib/grafana'
      - './src/grafana/provisioning:/etc/grafana/provisioning'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource  
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    restart: unless-stopped 
    networks: 
      - monitoring         